# Generated by Django 5.0.7 on 2024-08-03 14:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Brand',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('brand_name', models.CharField(max_length=200, unique=True)),
                ('brand_nation', models.CharField(max_length=200)),
            ],
        ),
        migrations.CreateModel(
            name='Phone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=200, unique=True)),
                ('color', models.CharField(max_length=200)),
                ('screen_size', models.PositiveIntegerField()),
                ('price', models.PositiveIntegerField()),
                ('region', models.CharField(max_length=200)),
                ('inventory_status', models.BooleanField(default=True)),
                ('brand', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='phones', to='phone_app.brand')),
            ],
        ),
    ]
