# Generated by Django 5.0.7 on 2024-08-03 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='phone',
            name='screen_size',
            field=models.FloatField(),
        ),
    ]
