# Generated by Django 5.0.7 on 2024-08-04 10:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phone_app', '0002_alter_phone_screen_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='phone',
            name='slug',
            field=models.SlugField(blank=True, max_length=200, unique=True),
        ),
    ]
